src/middlewares/error.handler.middleware.js, src/migrations/20230102072551-create-users.js, src/models/users.js
=> Users 모델에 password 추가

package-lock.json, package.json, src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/routes/index.js, src/routes/users.route.js, src/util/encryption.js
=> ✨ 회원가입, 중복검사, 로그아웃 구현

package-lock.json, package.json, src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/architecture/services/users.service.js, src/migrations/20230102072629-create-medicines.js, src/models/medicines.js, src/routes/index.js, src/routes/products.route.js
=> :art: FIX: DB Medicines 구조 변경

src/migrations/20230102072551-create-users.js, src/models/users.js
🗃️ feat : image URL default 값 추가
=> 🗃️ feat : image URL default 값 추가

package-lock.json, package.json, src/architecture/controllers/users.controller.js, src/routes/index.js, src/routes/login.route.js, src/routes/products.route.js, src/routes/users.route.js
=> 🐛 fix : 전체적인 에러 수정

.aws/task-definition.json, src/middlewares/authUser.middleware.js
=> 🔒 feat : 환경변수 추가

src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/migrations/20230102072551-create-users.js, src/models/users.js
#32 🗃️ Users phoneNumber 칼럼 추가 및 저장
phoneNumber 칼럼 추가하였고 회원가입 시 휴대폰번호도 같이 저장하게 수정하였습니다.
=> #32 🗃️ Users phoneNumber 칼럼 추가 및 저장

src/architecture/controllers/users.controller.js
#32  🎨 phoneNumber validation 수정
String 값으로 수정, 길이 11자로 제한, 0부터 9까지만 가능
=> #32 🎨 phoneNumber validation 수정

src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/migrations/20230102072629-create-medicines.js, src/models/medicines.js, src/routes/products.route.js
검색 기능 1차 구현 완료입니다.
sequelize의 Op.or와 Op.like 매서드를 활용 하였고, %라는 검색 와일드카드를 사용하여 검색어가 포함된 모든 검색결과를 가져오도록 구현하였습니다.
검색 결과는 아래와 같이 나옵니다.
```
[
{
"medicineId": 11,
"itemName": "제일에페드린염산염주사액4%",
"entpName": "(주)제일제약",
"etcOtcCode": "전문의약품",
"productType": "",
"itemImage": null
}, 
...
]
```
추가 디테일적인 부분은 디자인 확인 후 프론트와 상의하여 수정 할 예정이며 아래 내용이 수정 될 예정입니다.
1. 최대 검색결과 개수
2. 검색결과 순서
3. 검색 타입을 넣을 지 말지 (현재는 통합검색으로 진행중)
=> :sparkles: #36 FEAT: 검색 기능 1차 구현

src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/routes/users.route.js
#38 , #39  ✨ 아이디, 비밀번호 찾기 구현
휴대폰을 통해 아이디 찾기 및 비밀번호 찾기를 구현하였습니다. 휴대폰 인증은 람다로 따로 구현하였으며 비밀번호 찾기 시 동일한 비밀번호로 변경을 시도하면 에러를 뜨게 구현하였습니다.
=> #38, 39 ✨ 아이디, 비밀번호 찾기 구현

src/architecture/controllers/users.controller.js, src/architecture/repositories/login.repository.js, src/architecture/services/login.service.js, src/architecture/services/users.service.js, src/migrations/20230102072551-create-users.js, src/models/users.js, src/routes/users.route.js, src/util/formatDate.js
#40 ✨ feat : 유저 조회 구현
ec2에선 utc 기준으로 잡혀 아마 로그인 횟수 초기화 기준이 am 12:00이 아닐수도 있습니다.
=> #40 ✨ feat : 유저 조회 구현

src/architecture/controllers/posts.controller.js, src/architecture/controllers/users.controller.js, src/architecture/repositories/posts.repository.js, src/architecture/services/posts.service.js, src/migrations/20230110113641-create-posts.js, src/models/posts.js, src/routes/index.js, src/routes/post.route.js
#47 ✨ feat : 글귀 랜덤 조회 구현
건강글귀 생성 및 랜덤 조회 완료하였습니다. 새로운 테이블 Posts가 생성되었습니다.
=> #47 ✨ feat : 글귀 랜덤 조회 구현

src/migrations/20230102072629-create-medicines.js, src/migrations/20230110052717-create-material.js, src/migrations/20230110164714-create-ingredient.js, src/models/ingredients.js, src/models/materials.js, src/models/medicines.js
feature #50 
성분 상세 정보를 등록하고, 해당 정보를 의약품 마다 같이 전달하기 위하여 분리합니다.
추가되는 부분은 성분 테이블과 약과 성분을 이어주는 중간 테이블 입니다.
=> 🎨  #50 FEAT: 성분 테이블 분리 및 중간 테이블 생성

src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/routes/users.route.js
#55 🎨 feat : 유저 정보 변경 분리
프론트의 요청으로 닉네임 수정, 프로필 이미지 수정 나누었습니다.
=> #55 🎨 feat : 유저 정보 변경 분리

src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/migrations/20230110164716-create-ingredient.js, src/models/ingredients.js, src/models/materials.js, src/models/medicines.js
성분 테이블을 분리 후 약과 연결하는 중간 테이블을 만들었습니다.
성분 테이블에는 성분명, 단위, 설명 칼럼이 있습니다.
중간 테이블에는 용량 칼럼이 있습니다.
이 과정에서 총량은 기본 데이터의 totalAmount로 분리 되었습니다.
=> ⚡  #51 FIX: 성분 기능 개선

src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/routes/products.route.js
설명을 배열형식으로 넣어 업로드 할 수 있는 api를 구현하였습니다.
성분 기능 구현 완료입니다.
이슈 닫겠습니다!
=> :zap: #51 FEAT: 성분 설명 업로드 api 추가

package-lock.json, package.json, src/util/autoupdate.js
매주 화요일 오전 2시 DB 자동 업로드를 구현하였습니다.
=> :sparkles: #54 FEAT: CRON 라이브러리를 이용한 스케줄링

.aws/task-definition.json, src/passport/GoogleStrategy.js
#63 🔒 feat : 환경변수 추가
구글, 네이버 환경변수 추가입니다
=> #63 🔒 feat : 환경변수 추가

src/app.js, src/util/autoupdate.js
불필요한 콘솔이 찍혀 있었던 부분을 시작 메세지로 바꾸었습니다.
start 변수를 넣어줄 필요없어 삭제하였습니다.
=> :zap: FIX: 자동 업로드파트 불필요한 코드 정리

src/app.js, src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/routes/products.route.js
1. type : 검색 타입 ( itemName, productType )
2. value : 검색어
3. page : 페이지 번호
4. pageSize : 한 페이지에 보여질 개수
```
{
"searchLength": 2,
"data": [
{
"medicineId": 10866,
"itemName": "닥터베아제정",
"entpName": "(주)대웅제약",
"etcOtcCode": "일반의약품",
"productType": "건위소화제",
"itemImage": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/148647963523800122",
"savedCount": 2
},
...
}
```
중간 쿼리스트링에 \b가 숨어져 들어오는 이슈가 있었고, include의 수를 카운트 해서 정렬을 해 주는 등 처음 해보는 방식의 어려움이 있었습니다.
=> ⚡  #36 FIX: 검색 기능 디테일 추가

src/architecture/repositories/login.repository.js, src/architecture/repositories/users.repository.js, src/architecture/services/login.service.js, src/passport/GoogleStrategy.js, src/passport/NaverStrategy.js
#71 ✨ feat : 구글,네이버로그인카운트 추가 
구글, 네이버로 로그인 했을 때 하루 기준으로 한번만 카운트 되게 구현하였습니다.
+ 로컬에서 회원가입 시 loginType에 Local을 고정값으로 넣게끔 구현하였습니다.
=> #71 ✨ feat : 구글,네이버로그인카운트 추가

src/architecture/repositories/products.repository.js
pageSize 변수가 Number 값으로 들어가지 않는 부분 수정
=> :zap: #36 FIX: 코드 수정

.aws/task-definition.json, src/passport/kakaoStrategy.js
=> #71 ✨ feat : 카카오 로그인 카운트 구현

src/architecture/controllers/users.controller.js
=> #78 🐛  fix : 정규표현식 수정

src/architecture/controllers/login.controller.js
=> 🐛 fix : 롤백

src/architecture/services/login.service.js, src/passport/KakaoStrategy.js
#85  🎨 fix : 아이디,비번  다를 시 에러 통일
아이디와 비번이 다를 시 에러를 통일하였습니다.
=> #85 🎨 fix : 아이디,비번  다를 시 에러 통일

src/architecture/controllers/login.controller.js, src/architecture/controllers/users.controller.js
#90 🐛 fix : 패스워드 벨리데이션 수정
로그인 할 때, 비밀번호 찾기 할 때 벨리데이션을 수정하였습니다.
=> #90 🐛 fix : 패스워드 벨리데이션 수정

src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/routes/users.route.js
#96 ✨ feat : 이메일로 휴대폰번호 찾기 구현
아이디 찾기, 비밀번호 찾기 시 로컬로 가입한 사람만 찾아지게끔 구현하였습니다.
+ 비밀번호 찾기 시 이메일을 입력하면 회원가입 시 입력한 휴대폰 번호를 가져와 고정값으로 둬 그 휴대폰 번호로 인증을 해야만 비밀번호를 수정하게끔 구현하였습니다.
=> #96✨ feat : 이메일로 휴대폰번호 찾기 구현

.aws/task-definition.json, src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/routes/users.route.js
#100 🔒  feat : 환경변수 설정
ICON_URL의 환경변수 값을 추가하였습니다.
=> #100 🔒  feat : 환경변수 설정

src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/middlewares/authCheck.middleware.js, src/routes/products.route.js
1. 비 로그인 시 userId가 null인 미들웨어 생성
2. 검색 시 찜 여부 확인 (dibs를 불리언으로 넘겨줌)
3. 약 타입 각각 분리하여 배열로 넘겨주기
4. 약 이름 괄호 이후 삭제
```
{
"medicineId": 506,
"itemName": "게보린정",
"entpName": "삼진제약(주)",
"etcOtcCode": "일반의약품",
"productType": [
"해열",
"진통",
"소염제"
],
"itemImage": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1N5PLuAiUvi",
"dibs": true
}
```
=> ⚡  #106 FIX : 검색 기능 디테일 추가

src/architecture/controllers/products.controller.js, src/architecture/repositories/products.repository.js, src/architecture/services/products.service.js, src/middlewares/authCheck.middleware.js, src/routes/products.route.js
1.  찜 여부
2.  효능효과 등 첫번째 줄 삭제
3.  약 타입 나눠 배열로 넘겨주기
4.  이름 괄호 이후 없애기
=> ⚡  #107 FIX : 상세보기, 비교하기 페이지 디테일 수정

src/architecture/services/users.service.js, src/middlewares/authUser.middleware.js
#112 🎨 feat : 회원탈퇴 소셜로그인 수정
소셜로그인 회원탈퇴 시 따로 비밀번호 비교 하지않게 구현하였습니다.
유저 정보 조회 시 로그인 타입도 같이 보내도록 구현하였습니다.
=> #112 🎨 feat : 회원탈퇴 소셜로그인 수정

src/architecture/services/products.service.js
약품 타입에 제를 모두 붙혀달라는 요청이 있어 수정합니다.
```
//기존
"productType": [
"해열",
"진통",
"소염제"
],
//변경
"productType": [
"해열제",
"진통제",
"소염제"
],
```
=> :zap: #106 #107 FIX : 약품 타입 개선 요청

src/architecture/repositories/users.repository.js
#119 🐛 fix : 로그아웃 토큰 값 변경
리프레쉬토큰에 ''은 못 와 500에러가 떠 null값으로 업데이트 하는 방식으로 변경하였습니다.
=> #119 🐛 fix : 로그아웃 토큰 값 변경

src/architecture/services/products.service.js, src/middlewares/authCheck.middleware.js, src/util/autoupdate.js
=> 🎨  Fix : detail

package.json, src/architecture/controllers/login.controller.js, src/passport/GoogleStrategy.js, src/passport/KakaoStrategy.js, src/passport/NaverStrategy.js
네이버 소셜 로그인 하면서 이메일 중복 체크 문제로 중복 에러 코드 삭제했습니다.
=> 🚑 #122 FIX : local Login과 소셜로그인 이메일 중복 체크 코드 삭제

src/architecture/services/users.service.js, src/passport/GoogleStrategy.js, src/passport/KakaoStrategy.js, src/passport/NaverStrategy.js
=> #127 🐛 fix : 한글 인코딩문제 해결

src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js
#127 🐛 fix : 파일네임 인코딩 및 쿼리로 수정
s3에서 url이 인코딩 된 값으로 들어오기에 수정하였으나 인코딩 된 값을 또 인코딩하는 경우가 되버려 수정하였습니다.
GET메소드인데 body값을 요구하여 query로 수정 후 이메일 찾기 시 이미지Url로 같이 보내달라는 프론트 요구에 맞게 수정하였습니다.
=> #127 🐛 fix : 파일네임 인코딩 및 쿼리로 수정

package.json
=> :art: FIX : 사용하지 않는 라이브러리 정리

src/architecture/services/products.service.js
=> :art: #135 FIX : 검색 기능 수정

README.md, src/config/config.js
#144 🔥 fire : 코드 정리
config.js에 안 쓰는 코드를 정리하였습니다.
=> #144 🔥 fire : 코드 정리

src/architecture/controllers/allergies.controller.js, src/architecture/repositories/allergies.repository.js, src/architecture/repositories/products.repository.js, src/architecture/services/allergies.service.js, src/architecture/services/products.service.js, src/migrations/20230122112544-create-allergies.js, src/models/allergies.js, src/models/users.js, src/routes/allergies.route.js, src/routes/index.js
=> ✨  #150 FEAT : 알러지 기능 구현

package-lock.json, src/architecture/controllers/review.controller.js, src/migrations/20230112072646-create-reivews.js, src/models/medicines.js, src/models/reviews.js, src/routes/index.js
🗃️  #147 FEAT : Models와 Migrations 생성 
리뷰기능 구현을 위해 리뷰 관련 model 생성하였고 migrate 했습니다.
=> 🗃️  #147 DOCS : Models와 Migrations 생성

src/models/users.js
conflict 해결 하던 중 실수코드 발견해서 수정하였습니다.
=> :ambulance: # 147 FIX : 실수코드 수정

.aws/task-definition.json, src/app.js, src/architecture/services/users.service.js
#162 👷 CI/CD 수정
서버 재배포로 인한 CI/CD 수정하였습니다.
=> #162 👷 CI/CD 수정

src/architecture/services/users.service.js
#164 🎨 feat : 유저 정보 조회 시 유저아이디 추가
프론트요청에 따라 추가하였습니다.
=> #164 🎨 feat : 유저 정보 조회 시 유저아이디 추가

src/architecture/services/users.service.js
#166 🐛 fix : 이메일 중복 검사 추가
회원가입 하기 전 한번 더 중복검사를 추가하기로 하여 구현하였습니다.
=> #166 🐛 fix : 이메일 중복 검사 추가

src/architecture/controllers/allergies.controller.js, src/architecture/services/products.service.js, src/architecture/services/users.service.js, src/config/config.js, src/util/autoupdate.js
#167 🔊 feat : 시퀄라이즈  로그 false 및 콘솔로그 정리
시퀄라이즈 콘솔때문에 로그가 너무 많아서 로그가 확인불가하여 정리하였습니다.
추가로 콘솔로그 또한 정리하였습니다.
=> #167 🔊 feat : 시퀄라이즈  로그 false 및 콘솔로그 정리

src/app.js, src/architecture/controllers/review.controller.js, src/architecture/controllers/reviews.controller.js, src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js, src/middlewares/authCheck.middleware.js, src/migrations/20230112072646-create-reivews.js, src/migrations/20230122112545-create-likes.js, src/migrations/20230122112550-create-likes.js, src/models/dislikes.js, src/models/likes.js, src/models/reviews.js, src/models/users.js, src/routes/index.js, src/routes/reviews.route.js
#159 FEAT : 리뷰 기능 구현 완료
- 리뷰 작성
- 리뷰 조회 (+like/dislike/likeCount/dislikeCount)
- 리뷰 수정
- 리뷰 삭제
기능 구현 완료했습니다
=> ✨ #159 FEAT : 리뷰 기능 구현

src/architecture/controllers/login.controller.js, src/architecture/services/reviews.service.js
소셜 로그인 redirect url 수정:
https://pillnuts.vercel.app/login/loading 에서 https://www.pillnuts.store/login/loading 으로 수정했습니다.
=> :truck: #173 FIX : 소셜 로그인 redirect url 수정

src/architecture/controllers/reviews.controller.js, src/architecture/services/reviews.service.js, src/middlewares/authCheck.middleware.js, src/migrations/20230112072646-create-reivews.js
#175 🎨 fix : 코드 구조 개선
콘솔로그 제거 및 프리티어 적용, 안 쓰는 코드 주석처리 하였습니다.
=> #175 🎨 fix : 코드 구조 개선

src/architecture/controllers/reviews.controller.js, src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js, src/migrations/20230122112551-create-dislikes.js, src/models/index.js, src/routes/login.route.js, src/routes/reviews.route.js
- 테스트 중 버그 발생해서 에러코드 수정했습니다.
- 프리티어 적용했습니다.
=> :bug: #159 FIX : 에러 코드 수정

src/architecture/controllers/reviews.controller.js, src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js, src/migrations/20230112072645-create-reivews.js, src/migrations/20230112072646-create-reviews.js, src/migrations/20230122112549-create-likes.js, src/migrations/20230122112552-create-dislikes.js, src/migrations/20230122112552-create-likes.js, src/migrations/20230122112554-create-dislikes.js, src/models/reviews.js
프론트 쪽의 요청으로,
- 리뷰 조회시 검색 기능 구현
- 리뷰 조회시 최신순으로 값 보내주기
- 마이페이지 리뷰에서 약 정보까지 보내주기
구현했습니다.
=> ✨ #184 FEAT : 리뷰 기능 추가

src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js
프론트 요청으로 리뷰 조회시 imageUrl 추가 해주었습니다.
=> :zap: #189 FIX : 리뷰 조회시 유저의 imageUrl 추가

src/architecture/controllers/reviews.controller.js, src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js
리뷰 조회시 기존에 구현했던 최신순 정렬에 도움돼요 순 정렬도 추가하였습니다.
=> :zap: #193 FIX : 리뷰 조회시 도움돼요 순으로 정렬 추가

package-lock.json, package.json, src/middlewares/login.middleware.js, src/middlewares/rateLimit.middleware.js, src/routes/users.route.js
#196 ✨ feat : Rate Limit 미들웨어 구현 및 적용
IP당 3분에 한번만 요청가능한 미들웨어를 구현하여 이메일 인증, 휴대폰 인증에 적용시켰습니다.
=> #196 ✨ feat : Rate Limit 미들웨어 구현 및 적용

src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/routes/users.route.js
#198 🐛 fix : 이메일 찾기 수정
아이디 찾기 시 해당 휴대폰 번호로 가입된 모든 아이디를 가져옵니다.
=> #198 🐛 fix : 이메일 찾기 수정

src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/routes/users.route.js
#201 🚑 feat : 이메일 찾기 롤백 및 휴대폰 중복검사 추가
회의한 결과 휴대폰 하나당 회원가입 한번만 가능하게 하기로 하였고 거기에 필요한 휴대폰 번호 중복검사를 추가로 구현하였습니다. 또한 이메일 찾기가 다시 findOne을 쓰면 되서 롤백하였습니다.
=> #201 🚑 feat : 이메일 찾기 롤백 및 휴대폰 중복검사 추가

src/architecture/controllers/users.controller.js, src/architecture/repositories/users.repository.js, src/architecture/services/users.service.js, src/middlewares/rateLimit.middleware.js, src/routes/users.route.js
#204 🚑 fix : Rate Limit 미들웨어 에러 수정
API 당 요청이 제한되서 우선 수정하였고 정확한 값을  알기위해 콘솔로그를 나둔 채로 배포하였습니다.
=> #204 🚑 fix : Rate Limit 미들웨어 에러 수정

src/architecture/services/users.service.js, src/middlewares/rateLimit.middleware.js, src/routes/users.route.js
#204 🚑 fix : Rate Limit 미들웨어 딜레이 추가
응답이 오기 전에 전송버튼을 누르면 여러번 전송이 가능한 버그가 있어 딜레이를 추가하였습니다.
=> #204 🚑 fix : Rate Limit 미들웨어 딜레이 추가

src/util/token.js
#211 🚑 fix : 토큰 유효시간 수정
테스트를 위한 토큰시간 수정입니다.
=> #211 🚑 fix : 토큰 유효시간 수정

src/app.js
=> #221 🐛 fix : CORS 오픈

src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js
기존 sequelize count 문법을 통해 불러오던 like와 dislike 갯수를 따로 불러와 버그를 해결했습니다.
=> 🐛  #231 FIX: 도움 돼요, 도움 안돼요 버튼 수정

src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/routes/users.route.js
#239 🔥 fix : 이메일 인증 삭제
이메일 인증을 빼기로 하여 삭제합니다.
=> #239 🔥 fix : 이메일 인증 삭제

.aws/task-definition.json
#248 👷 fix : 인스턴스 사양 변경
c4.xlarge에서 t3a.small로 변경 후 재배포하여 컨테이너 할당되는 cpu, memory 수정하였습니다.
=> #248 👷 fix : 인스턴스 사양 변경

package-lock.json, package.json, src/app.js
#254 🔒 feat : helmet 설정 추가
보안을 위해 helmet 설정을 추가하였습니다. 디폴트값으로 설정하였습니다.
=> #254 🔒 feat : helmet 설정 추가

src/app.js
#213 🔒 fix : Cors Origin 수정
와일드카드에서 https://www.pillnuts.store, http://localhost:3000 변경하였습니다.
=> #213 🔒 fix : Cors Origin 수정

src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/util/formatDate.js
#266 🎨 refactor : 날짜 padStart로 수정
if문을 padstart로 변경하였습니다.
=> #266 🎨 refactor : 날짜 padStart로 수정

src/architecture/controllers/login.controller.js, src/architecture/controllers/users.controller.js, src/architecture/services/users.service.js, src/util/formatDate.js, src/util/joi.js
#269 🎨 refactor : Joi 에러메세지 커스텀
Joi 에러메세지를 커스텀하고 함수로 뺐습니다.
=> #269 🎨 refactor : Joi 에러메세지 커스텀

src/architecture/controllers/users.controller.js, src/util/joi.js
#269 🚑 fix : certification Joi 추가
certification 밸린데이션 추가 및 불필요한 코드 삭제
=> #269 🚑 fix : certification Joi 추가

swagger-output.json
#279 🐛 fix : swagger 스키마 수정
CORS 에러를 해결하기위해 스키마 https도 추가하였습니다.
=> #279 🐛 fix : swagger 스키마 수정

src/app.js, src/architecture/controllers/login.controller.js, src/architecture/repositories/login.repository.js, src/architecture/services/login.service.js
app.js와 architecture 폴더 중 login 파일들 불필요한 주석 삭제했습니다.
=> :bulb: FIX: 불필요한 주석 삭제

swagger-output.json
#279 🐛 fix : swagger 수정
배포버전으로 수정하였습니다.
=> #279 🐛 fix : swagger 수정

swagger-output.json
실수로 빠트린 description 부분 추가해주었습니다.
=> :art: FIX : 알러지 등록/삭제 description 추가
